-- ============================================================
-- Vermont Medicaid PMPM Reconciliation SFY2022
-- Data Load Script - Run in DBeaver against medicaid_pmpm DB
-- ============================================================

-- TRUNCATE first so re-runs are idempotent
TRUNCATE TABLE budget_reference CASCADE;
TRUNCATE TABLE reconciliation CASCADE;
TRUNCATE TABLE findings_log CASCADE;

-- ============================================================
-- 1. budget_reference
-- ============================================================
INSERT INTO budget_reference (meg, avg_monthly_enrollment, gross_pmpm, premium_pmpm, net_pmpm, annual_budget_est) VALUES ('ABD Adult', 6475, 764.19, 0, 764.19, 59377563.0);
INSERT INTO budget_reference (meg, avg_monthly_enrollment, gross_pmpm, premium_pmpm, net_pmpm, annual_budget_est) VALUES ('ABD Dual', 17649, 257.64, 0, 257.64, 54565060.32);
INSERT INTO budget_reference (meg, avg_monthly_enrollment, gross_pmpm, premium_pmpm, net_pmpm, annual_budget_est) VALUES ('General Adult', 10049, 502.44, 0, 502.44, 60588234.72);
INSERT INTO budget_reference (meg, avg_monthly_enrollment, gross_pmpm, premium_pmpm, net_pmpm, annual_budget_est) VALUES ('New Adult Childless', 35802, 470.11, 0, 470.11, 201970538.64);
INSERT INTO budget_reference (meg, avg_monthly_enrollment, gross_pmpm, premium_pmpm, net_pmpm, annual_budget_est) VALUES ('New Adult w/Child', 22258, 404.75, 0, 404.75, 108107106.0);
INSERT INTO budget_reference (meg, avg_monthly_enrollment, gross_pmpm, premium_pmpm, net_pmpm, annual_budget_est) VALUES ('Vermont Premium Assist.', 15937, 29.36, 0, 29.36, 5614923.84);
INSERT INTO budget_reference (meg, avg_monthly_enrollment, gross_pmpm, premium_pmpm, net_pmpm, annual_budget_est) VALUES ('Vermont Cost Sharing', 3236, 29.12, 0, 29.12, 1130787.84);
INSERT INTO budget_reference (meg, avg_monthly_enrollment, gross_pmpm, premium_pmpm, net_pmpm, annual_budget_est) VALUES ('ABD Child', 1594, 1068.01, 0, 1068.01, 20428895.28);
INSERT INTO budget_reference (meg, avg_monthly_enrollment, gross_pmpm, premium_pmpm, net_pmpm, annual_budget_est) VALUES ('General Child', 59588, 224.4, 0, 224.4, 160458566.4);
INSERT INTO budget_reference (meg, avg_monthly_enrollment, gross_pmpm, premium_pmpm, net_pmpm, annual_budget_est) VALUES ('Underinsured Child', 530, 68.19, 0, 68.19, 433688.4);
INSERT INTO budget_reference (meg, avg_monthly_enrollment, gross_pmpm, premium_pmpm, net_pmpm, annual_budget_est) VALUES ('CHIP', 4374, 165.45, 0, 165.45, 8684139.6);
INSERT INTO budget_reference (meg, avg_monthly_enrollment, gross_pmpm, premium_pmpm, net_pmpm, annual_budget_est) VALUES ('Pharmacy Only', 9568, 47.5, 0, 47.5, 5453760.0);
INSERT INTO budget_reference (meg, avg_monthly_enrollment, gross_pmpm, premium_pmpm, net_pmpm, annual_budget_est) VALUES ('Choices for Care', 4596, 727.16, 0, 727.16, 40104328.32);

-- ============================================================
-- 2. reconciliation
-- ============================================================
INSERT INTO reconciliation (meg, budget_enrollment, actual_enrollment, enrollment_variance, enrollment_variance_pct, budget_pmpm, actual_pmpm, pmpm_variance, pmpm_variance_pct, budget_ann_cost, actual_ann_cost, cost_impact) VALUES ('ABD Adult', 6475, 6521, 46, 0.007104, 764.19, 764.19, 0.0, 0.0, 59377563.0, 59799395.88, 421832.88);
INSERT INTO reconciliation (meg, budget_enrollment, actual_enrollment, enrollment_variance, enrollment_variance_pct, budget_pmpm, actual_pmpm, pmpm_variance, pmpm_variance_pct, budget_ann_cost, actual_ann_cost, cost_impact) VALUES ('ABD Dual', 17649, 17649, 0, 0.0, 257.64, 261.82, 4.18, 0.016224, 54565060.32, 55450334.16, 885273.84);
INSERT INTO reconciliation (meg, budget_enrollment, actual_enrollment, enrollment_variance, enrollment_variance_pct, budget_pmpm, actual_pmpm, pmpm_variance, pmpm_variance_pct, budget_ann_cost, actual_ann_cost, cost_impact) VALUES ('General Adult', 10049, 10049, 0, 0.0, 502.44, 502.44, 0.0, 0.0, 60588234.72, 60588234.72, 0.0);
INSERT INTO reconciliation (meg, budget_enrollment, actual_enrollment, enrollment_variance, enrollment_variance_pct, budget_pmpm, actual_pmpm, pmpm_variance, pmpm_variance_pct, budget_ann_cost, actual_ann_cost, cost_impact) VALUES ('New Adult Childless', 35802, 36104, 302, 0.008435, 470.11, 470.11, 0.0, 0.0, 201970538.64, 203674217.28, 1703678.64);
INSERT INTO reconciliation (meg, budget_enrollment, actual_enrollment, enrollment_variance, enrollment_variance_pct, budget_pmpm, actual_pmpm, pmpm_variance, pmpm_variance_pct, budget_ann_cost, actual_ann_cost, cost_impact) VALUES ('New Adult w/Child', 22258, 22258, 0, 0.0, 404.75, 398.63, -6.12, -0.01512, 108107106.0, 106472478.48, -1634627.52);
INSERT INTO reconciliation (meg, budget_enrollment, actual_enrollment, enrollment_variance, enrollment_variance_pct, budget_pmpm, actual_pmpm, pmpm_variance, pmpm_variance_pct, budget_ann_cost, actual_ann_cost, cost_impact) VALUES ('Vermont Premium Assist.', 15937, 15937, 0, 0.0, 29.36, 29.36, 0.0, 0.0, 5614923.84, 5614923.84, 0.0);
INSERT INTO reconciliation (meg, budget_enrollment, actual_enrollment, enrollment_variance, enrollment_variance_pct, budget_pmpm, actual_pmpm, pmpm_variance, pmpm_variance_pct, budget_ann_cost, actual_ann_cost, cost_impact) VALUES ('Vermont Cost Sharing', 3236, 3236, 0, 0.0, 29.12, 29.12, 0.0, 0.0, 1130787.84, 1130787.84, 0.0);
INSERT INTO reconciliation (meg, budget_enrollment, actual_enrollment, enrollment_variance, enrollment_variance_pct, budget_pmpm, actual_pmpm, pmpm_variance, pmpm_variance_pct, budget_ann_cost, actual_ann_cost, cost_impact) VALUES ('ABD Child', 1594, 1594, 0, 0.0, 1068.01, 1092.47, 24.46, 0.022902, 20428895.28, 20896766.16, 467870.88);
INSERT INTO reconciliation (meg, budget_enrollment, actual_enrollment, enrollment_variance, enrollment_variance_pct, budget_pmpm, actual_pmpm, pmpm_variance, pmpm_variance_pct, budget_ann_cost, actual_ann_cost, cost_impact) VALUES ('General Child', 59588, 59588, 0, 0.0, 224.4, 224.4, 0.0, 0.0, 160458566.4, 160458566.4, 0.0);
INSERT INTO reconciliation (meg, budget_enrollment, actual_enrollment, enrollment_variance, enrollment_variance_pct, budget_pmpm, actual_pmpm, pmpm_variance, pmpm_variance_pct, budget_ann_cost, actual_ann_cost, cost_impact) VALUES ('Underinsured Child', 530, 487, -43, -0.081132, 68.19, 68.19, 0.0, 0.0, 433688.4, 398502.36, -35186.04);
INSERT INTO reconciliation (meg, budget_enrollment, actual_enrollment, enrollment_variance, enrollment_variance_pct, budget_pmpm, actual_pmpm, pmpm_variance, pmpm_variance_pct, budget_ann_cost, actual_ann_cost, cost_impact) VALUES ('CHIP', 4374, 4374, 0, 0.0, 165.45, 165.45, 0.0, 0.0, 8684139.6, 8684139.6, 0.0);
INSERT INTO reconciliation (meg, budget_enrollment, actual_enrollment, enrollment_variance, enrollment_variance_pct, budget_pmpm, actual_pmpm, pmpm_variance, pmpm_variance_pct, budget_ann_cost, actual_ann_cost, cost_impact) VALUES ('Pharmacy Only', 9568, 9568, 0, 0.0, 47.5, 47.5, 0.0, 0.0, 5453760.0, 5453760.0, 0.0);
INSERT INTO reconciliation (meg, budget_enrollment, actual_enrollment, enrollment_variance, enrollment_variance_pct, budget_pmpm, actual_pmpm, pmpm_variance, pmpm_variance_pct, budget_ann_cost, actual_ann_cost, cost_impact) VALUES ('Choices for Care', 4596, 4721, 125, 0.027198, 727.16, 727.16, 0.0, 0.0, 40104328.32, 41195068.32, 1090740.0);

-- ============================================================
-- 3. findings_log
-- ============================================================
INSERT INTO findings_log (meg, variance_type, budget_figure, actual_figure, variance, variance_pct, finding_root_cause, resolution_status) VALUES ('ABD Adult', 'Enrollment', '6475', '6521', '+46', '+0.71%', 'Actual enrollment exceeded projection by 46 members. Consistent with statewide trend of increased ABD enrollment post-PHE. No PMPM variance detected.', 'RESOLVED — Variance within acceptable range (<1%). Noted for actuarial review in next budget cycle. GP 9/15/22');
INSERT INTO findings_log (meg, variance_type, budget_figure, actual_figure, variance, variance_pct, finding_root_cause, resolution_status) VALUES ('ABD Dual', 'PMPM Cost', '$257.64', '$261.82', '+$4.18', '+1.62%', 'Actual PMPM exceeded budget by $4.18 (1.62%). Likely driven by increased utilization of dual-eligible services and higher pharmacy costs in Q4 SFY2022. Enrollment matched projection.', 'RESOLVED — Variance under 2.0% threshold. Flagged for monitoring in SFY2023 actuarial update. GP 9/15/22');
INSERT INTO findings_log (meg, variance_type, budget_figure, actual_figure, variance, variance_pct, finding_root_cause, resolution_status) VALUES ('New Adult Childless', 'Enrollment', '35802', '36104', '+302', '+0.84%', 'Enrollment exceeded projection by 302 members. PHE continuous enrollment provisions prevented disenrollment of members who would otherwise have lost eligibility. Expected to normalize post-PHE unwinding.', 'RESOLVED — PHE-related variance documented. AHS and JFO notified. Projection to be revised in next budget cycle. GP 9/15/22');
INSERT INTO findings_log (meg, variance_type, budget_figure, actual_figure, variance, variance_pct, finding_root_cause, resolution_status) VALUES ('New Adult w/Child', 'PMPM Cost', '$404.75', '$398.63', '($6.12)', '(1.51%)', 'Actual PMPM came in $6.12 below budget. Favorable variance attributable to lower-than-projected inpatient utilization and shift toward telehealth services with lower unit costs.', 'RESOLVED — Favorable variance. No corrective action required. Documented for budget performance report. GP 9/15/22');
INSERT INTO findings_log (meg, variance_type, budget_figure, actual_figure, variance, variance_pct, finding_root_cause, resolution_status) VALUES ('ABD Child', 'PMPM Cost', '$1,068.01', '$1,092.47', '+$24.46', '+2.29%', 'PMPM exceeded budget by $24.46 (2.29%) — above the 2.0% threshold. ABD Child population has high acuity and is sensitive to utilization changes. Increased long-term care and behavioral health claims identified as primary drivers.', 'ESCALATED — Variance exceeds threshold. Referred to actuarial team for detailed claims analysis. Written response required from provider community. GP 9/15/22');
INSERT INTO findings_log (meg, variance_type, budget_figure, actual_figure, variance, variance_pct, finding_root_cause, resolution_status) VALUES ('Underinsured Child', 'Enrollment', '530', '487', '(43)', '(8.11%)', 'Enrollment fell 43 members below projection (8.11% variance). Significant drop likely reflects transition of previously underinsured children to full Medicaid coverage under PHE continuous enrollment provisions.', 'RESOLVED — PHE enrollment shift confirmed with eligibility team. Members confirmed enrolled in General Child MEG. No financial exposure. GP 9/15/22');
INSERT INTO findings_log (meg, variance_type, budget_figure, actual_figure, variance, variance_pct, finding_root_cause, resolution_status) VALUES ('Choices for Care', 'Enrollment', '4596', '4721', '+125', '+2.72%', 'Enrollment exceeded projection by 125 members (2.72%). Choices for Care is a high-cost HCBS waiver program. Additional enrollment has significant budget impact given $727.16 PMPM. Total annual cost impact approximately $1.09M above budget.', 'ESCALATED — High-impact variance. Budget amendment request submitted to Finance and Management. DAIL notified. Monitoring monthly. GP 9/15/22');

INSERT INTO findings_log (meg, variance_type, budget_figure, actual_figure, variance, variance_pct, finding_root_cause, resolution_status) VALUES ('General Adult', 'None', 'N/A', 'N/A', '$0.00', '0.00%', 'No material variance detected. Enrollment and PMPM both matched budget figures exactly. No action required.', 'CLOSED — Within threshold. No findings. GP 9/15/22');
INSERT INTO findings_log (meg, variance_type, budget_figure, actual_figure, variance, variance_pct, finding_root_cause, resolution_status) VALUES ('Vermont Premium Assist.', 'None', 'N/A', 'N/A', '$0.00', '0.00%', 'No material variance detected. Enrollment and PMPM both matched budget figures exactly. No action required.', 'CLOSED — Within threshold. No findings. GP 9/15/22');
INSERT INTO findings_log (meg, variance_type, budget_figure, actual_figure, variance, variance_pct, finding_root_cause, resolution_status) VALUES ('Vermont Cost Sharing', 'None', 'N/A', 'N/A', '$0.00', '0.00%', 'No material variance detected. Enrollment and PMPM both matched budget figures exactly. No action required.', 'CLOSED — Within threshold. No findings. GP 9/15/22');
INSERT INTO findings_log (meg, variance_type, budget_figure, actual_figure, variance, variance_pct, finding_root_cause, resolution_status) VALUES ('General Child', 'None', 'N/A', 'N/A', '$0.00', '0.00%', 'No material variance detected. Enrollment and PMPM both matched budget figures exactly. No action required.', 'CLOSED — Within threshold. No findings. GP 9/15/22');
INSERT INTO findings_log (meg, variance_type, budget_figure, actual_figure, variance, variance_pct, finding_root_cause, resolution_status) VALUES ('CHIP', 'None', 'N/A', 'N/A', '$0.00', '0.00%', 'No material variance detected. Enrollment and PMPM both matched budget figures exactly. No action required.', 'CLOSED — Within threshold. No findings. GP 9/15/22');
INSERT INTO findings_log (meg, variance_type, budget_figure, actual_figure, variance, variance_pct, finding_root_cause, resolution_status) VALUES ('Pharmacy Only', 'None', 'N/A', 'N/A', '$0.00', '0.00%', 'No material variance detected. Enrollment and PMPM both matched budget figures exactly. No action required.', 'CLOSED — Within threshold. No findings. GP 9/15/22');

-- Quick row-count check
SELECT 'budget_reference' AS tbl, COUNT(*) FROM budget_reference
UNION ALL SELECT 'reconciliation', COUNT(*) FROM reconciliation
UNION ALL SELECT 'findings_log', COUNT(*) FROM findings_log;
